name: Build and deploy ASP.Net Core app to Azure Web App - dotnetwebapp570

on:
  push:
    branches:
      - master # Consider changing to 'main' if you use the default branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x' # Ensure this version matches your project requirements
          include-prerelease: true

      - name: Restore NuGet packages
        run: nuget restore CRUD application 2.sln # Replace CRUD Apllication 2.sln with the path to your solution file if necessary

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore # No need to restore again, as NuGet packages are already restored

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-build # Avoid rebuilding

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dotnetwebapp570' # Ensure this matches your Azure Web App name
          slot-name: 'Production' # Ensure correct casing
          package: ${{env.DOTNET_ROOT}}/myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FC0B89ED487345D78C43744649199CC8 }}
